### PR TITLE
Add climits #include

### PR DESCRIPTION
**Pull request by ghost**
Needed for Linux and other Unix-likes.

### CODE REVIEW

**Comment by nhurde** [comment]
Can you explain reason for placing the climits in this header versus deeper or higher in engine/editor?

**Comment by time-killer-games** [comment]
It is only needed here for it to build, but i wasn't sure where you wanted it to begin with.

**Comment by nhurde** [comment]
See if placing in gpe/gpe_common_includes.h has any problems.

You placed this within the sdl2 module, so that wouldnt apply to the raylib, sfml and other potential modules.

**Comment by time-killer-games** [comment]
Thanks! I didn't know you had a dedicated include for common includes, that's very ingenious and I never though to do something like that before, I just might have to copy your idea for some of my projects at some point :D

**Pull request merged**
